# Generated by Django 2.0.2 on 2018-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentDetailed',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('cgpa', models.IntegerField()),
                ('yearOfStudy', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=250)),
                ('workEx', models.TextField()),
                ('publications', models.TextField()),
                ('certificates', models.TextField()),
                ('personalProjects', models.TextField()),
                ('skillsInterest', models.TextField()),
                ('hobbies', models.TextField()),
            ],
        ),
    ]
