# Generated by Django 2.0.2 on 2018-03-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDetailed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailed',
            name='branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='certificates',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='cgpa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='institute',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='personalProjects',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='publications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='skillsInterest',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='workEx',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='yearOfStudy',
            field=models.IntegerField(blank=True),
        ),
    ]
