# Generated by Django 2.0.2 on 2018-03-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDetailed', '0002_auto_20180321_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailed',
            name='workEx',
            field=models.IntegerField(blank=True),
        ),
    ]
