# Generated by Django 2.0.2 on 2018-04-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDetailed', '0003_auto_20180324_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailed',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='certificates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='cgpa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='institute',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='personalProjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='publications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='skillsInterest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='workEx',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='yearOfStudy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
