# Generated by Django 2.0.2 on 2018-04-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDetailed', '0005_auto_20180430_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetailed',
            name='cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
