# Generated by Django 2.0.2 on 2018-05-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentDetailed', '0006_auto_20180430_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailed',
            name='areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetailed',
            name='workEx',
            field=models.TextField(blank=True, null=True),
        ),
    ]
