# Generated by Django 2.0.2 on 2018-03-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profDetailed',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('areas', models.TextField()),
                ('keywords', models.TextField()),
                ('minWorkEx', models.PositiveIntegerField()),
                ('minYearOfStudy', models.PositiveIntegerField()),
                ('minCgpa', models.PositiveIntegerField()),
                ('branch', models.TextField()),
            ],
        ),
    ]
