# Generated by Django 2.0.2 on 2018-05-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profDetailed', '0005_auto_20180430_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='profdetailed',
            name='selectedStudents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
