# Generated by Django 2.0.2 on 2018-07-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profDetailed', '0006_profdetailed_selectedstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profdetailed',
            name='selectedStudents',
        ),
    ]
