# Generated by Django 2.0.2 on 2018-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profBasic',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('mobileNo', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('areas', models.TextField()),
                ('websiteLinks', models.TextField()),
            ],
        ),
    ]
