# Generated by Django 2.0.2 on 2018-03-21 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profBasic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profbasic',
            name='email',
        ),
    ]
