# Generated by Django 2.0.2 on 2018-03-21 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profBasic', '0002_remove_profbasic_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profbasic',
            name='age',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='areas',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='institute',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='mobileNo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profbasic',
            name='websiteLinks',
            field=models.TextField(blank=True),
        ),
    ]
