# Generated by Django 2.0.2 on 2018-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profBasic', '0004_auto_20180430_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='profbasic',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='images-data'),
        ),
    ]
